// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

struct NFTSettingsData {
  uint256 ticket;
  uint256 numOfGames;
  uint256 perRound;
  uint256 pieces;
}

library NFTSettings {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "", name: "NFTSettings", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x746200000000000000000000000000004e465453657474696e67730000000000);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0080040020202020000000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of (address, uint256)
  Schema constant _keySchema = Schema.wrap(0x00340200611f0000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (uint256, uint256, uint256, uint256)
  Schema constant _valueSchema = Schema.wrap(0x008004001f1f1f1f000000000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](2);
    keyNames[0] = "tokenAddr";
    keyNames[1] = "tokenId";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](4);
    fieldNames[0] = "ticket";
    fieldNames[1] = "numOfGames";
    fieldNames[2] = "perRound";
    fieldNames[3] = "pieces";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get ticket.
   */
  function getTicket(address tokenAddr, uint256 tokenId) internal view returns (uint256 ticket) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(tokenAddr)));
    _keyTuple[1] = bytes32(uint256(tokenId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get ticket.
   */
  function _getTicket(address tokenAddr, uint256 tokenId) internal view returns (uint256 ticket) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(tokenAddr)));
    _keyTuple[1] = bytes32(uint256(tokenId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set ticket.
   */
  function setTicket(address tokenAddr, uint256 tokenId, uint256 ticket) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(tokenAddr)));
    _keyTuple[1] = bytes32(uint256(tokenId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((ticket)), _fieldLayout);
  }

  /**
   * @notice Set ticket.
   */
  function _setTicket(address tokenAddr, uint256 tokenId, uint256 ticket) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(tokenAddr)));
    _keyTuple[1] = bytes32(uint256(tokenId));

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((ticket)), _fieldLayout);
  }

  /**
   * @notice Get numOfGames.
   */
  function getNumOfGames(address tokenAddr, uint256 tokenId) internal view returns (uint256 numOfGames) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(tokenAddr)));
    _keyTuple[1] = bytes32(uint256(tokenId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get numOfGames.
   */
  function _getNumOfGames(address tokenAddr, uint256 tokenId) internal view returns (uint256 numOfGames) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(tokenAddr)));
    _keyTuple[1] = bytes32(uint256(tokenId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set numOfGames.
   */
  function setNumOfGames(address tokenAddr, uint256 tokenId, uint256 numOfGames) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(tokenAddr)));
    _keyTuple[1] = bytes32(uint256(tokenId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((numOfGames)), _fieldLayout);
  }

  /**
   * @notice Set numOfGames.
   */
  function _setNumOfGames(address tokenAddr, uint256 tokenId, uint256 numOfGames) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(tokenAddr)));
    _keyTuple[1] = bytes32(uint256(tokenId));

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((numOfGames)), _fieldLayout);
  }

  /**
   * @notice Get perRound.
   */
  function getPerRound(address tokenAddr, uint256 tokenId) internal view returns (uint256 perRound) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(tokenAddr)));
    _keyTuple[1] = bytes32(uint256(tokenId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get perRound.
   */
  function _getPerRound(address tokenAddr, uint256 tokenId) internal view returns (uint256 perRound) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(tokenAddr)));
    _keyTuple[1] = bytes32(uint256(tokenId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set perRound.
   */
  function setPerRound(address tokenAddr, uint256 tokenId, uint256 perRound) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(tokenAddr)));
    _keyTuple[1] = bytes32(uint256(tokenId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((perRound)), _fieldLayout);
  }

  /**
   * @notice Set perRound.
   */
  function _setPerRound(address tokenAddr, uint256 tokenId, uint256 perRound) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(tokenAddr)));
    _keyTuple[1] = bytes32(uint256(tokenId));

    StoreCore.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((perRound)), _fieldLayout);
  }

  /**
   * @notice Get pieces.
   */
  function getPieces(address tokenAddr, uint256 tokenId) internal view returns (uint256 pieces) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(tokenAddr)));
    _keyTuple[1] = bytes32(uint256(tokenId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get pieces.
   */
  function _getPieces(address tokenAddr, uint256 tokenId) internal view returns (uint256 pieces) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(tokenAddr)));
    _keyTuple[1] = bytes32(uint256(tokenId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set pieces.
   */
  function setPieces(address tokenAddr, uint256 tokenId, uint256 pieces) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(tokenAddr)));
    _keyTuple[1] = bytes32(uint256(tokenId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((pieces)), _fieldLayout);
  }

  /**
   * @notice Set pieces.
   */
  function _setPieces(address tokenAddr, uint256 tokenId, uint256 pieces) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(tokenAddr)));
    _keyTuple[1] = bytes32(uint256(tokenId));

    StoreCore.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((pieces)), _fieldLayout);
  }

  /**
   * @notice Get the full data.
   */
  function get(address tokenAddr, uint256 tokenId) internal view returns (NFTSettingsData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(tokenAddr)));
    _keyTuple[1] = bytes32(uint256(tokenId));

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get(address tokenAddr, uint256 tokenId) internal view returns (NFTSettingsData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(tokenAddr)));
    _keyTuple[1] = bytes32(uint256(tokenId));

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(
    address tokenAddr,
    uint256 tokenId,
    uint256 ticket,
    uint256 numOfGames,
    uint256 perRound,
    uint256 pieces
  ) internal {
    bytes memory _staticData = encodeStatic(ticket, numOfGames, perRound, pieces);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(tokenAddr)));
    _keyTuple[1] = bytes32(uint256(tokenId));

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(
    address tokenAddr,
    uint256 tokenId,
    uint256 ticket,
    uint256 numOfGames,
    uint256 perRound,
    uint256 pieces
  ) internal {
    bytes memory _staticData = encodeStatic(ticket, numOfGames, perRound, pieces);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(tokenAddr)));
    _keyTuple[1] = bytes32(uint256(tokenId));

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(address tokenAddr, uint256 tokenId, NFTSettingsData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.ticket, _table.numOfGames, _table.perRound, _table.pieces);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(tokenAddr)));
    _keyTuple[1] = bytes32(uint256(tokenId));

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(address tokenAddr, uint256 tokenId, NFTSettingsData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.ticket, _table.numOfGames, _table.perRound, _table.pieces);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(tokenAddr)));
    _keyTuple[1] = bytes32(uint256(tokenId));

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(
    bytes memory _blob
  ) internal pure returns (uint256 ticket, uint256 numOfGames, uint256 perRound, uint256 pieces) {
    ticket = (uint256(Bytes.getBytes32(_blob, 0)));

    numOfGames = (uint256(Bytes.getBytes32(_blob, 32)));

    perRound = (uint256(Bytes.getBytes32(_blob, 64)));

    pieces = (uint256(Bytes.getBytes32(_blob, 96)));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   *
   *
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths,
    bytes memory
  ) internal pure returns (NFTSettingsData memory _table) {
    (_table.ticket, _table.numOfGames, _table.perRound, _table.pieces) = decodeStatic(_staticData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(address tokenAddr, uint256 tokenId) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(tokenAddr)));
    _keyTuple[1] = bytes32(uint256(tokenId));

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(address tokenAddr, uint256 tokenId) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(tokenAddr)));
    _keyTuple[1] = bytes32(uint256(tokenId));

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(
    uint256 ticket,
    uint256 numOfGames,
    uint256 perRound,
    uint256 pieces
  ) internal pure returns (bytes memory) {
    return abi.encodePacked(ticket, numOfGames, perRound, pieces);
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    uint256 ticket,
    uint256 numOfGames,
    uint256 perRound,
    uint256 pieces
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(ticket, numOfGames, perRound, pieces);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(address tokenAddr, uint256 tokenId) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(tokenAddr)));
    _keyTuple[1] = bytes32(uint256(tokenId));

    return _keyTuple;
  }
}
