// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Puzzle, PuzzleData } from "./tables/Puzzle.sol";
import { PlayableGames } from "./tables/PlayableGames.sol";
import { NFTSettings, NFTSettingsData } from "./tables/NFTSettings.sol";
import { GameRound, GameRoundData } from "./tables/GameRound.sol";
import { GameRecord, GameRecordData } from "./tables/GameRecord.sol";
import { PlayerGameRecord, PlayerGameRecordData } from "./tables/PlayerGameRecord.sol";
