// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Puzzle, PuzzleData } from "./tables/Puzzle.sol";
import { PlayableGames, PlayableGamesData } from "./tables/PlayableGames.sol";
import { NFTSettings, NFTSettingsData } from "./tables/NFTSettings.sol";
import { GameRound, GameRoundData } from "./tables/GameRound.sol";
import { GameRecord, GameRecordData } from "./tables/GameRecord.sol";
import { PlayerGameRecord, PlayerGameRecordData } from "./tables/PlayerGameRecord.sol";
import { GameActivityTimes } from "./tables/GameActivityTimes.sol";
import { PlayerClaim } from "./tables/PlayerClaim.sol";
import { PlayerWithdrawn } from "./tables/PlayerWithdrawn.sol";
import { RankRecord, RankRecordData } from "./tables/RankRecord.sol";
import { TotalSupply } from "./tables/TotalSupply.sol";
import { NFTData } from "./tables/NFTData.sol";
