// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { BonusSingle, BonusBatchResProfile, BonusBatchRank, BonusBatchResRank } from "../../libraries/Struct.sol";

/**
 * @title IBonusSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IBonusSystem {
  function getBonusSingle(BonusSingle memory bonusSingle, bool claimCheck) external view returns (uint256);

  function getBonusBatchProfile(BonusSingle[] memory bonusMuti) external view returns (BonusBatchResProfile[] memory);

  function getBonusBatchRank(BonusBatchRank memory bonusBatchRank) external view returns (BonusBatchResRank[] memory);

  function claimBonusSingle(BonusSingle memory bonusSingle) external;

  function claclaimBonusBatch(BonusSingle[] memory bonusSingle) external;
}
