// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { NFTInfo } from "../../libraries/Struct.sol";

/**
 * @title IPurchaseSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IPurchaseSystem {
  function purchaseGame(NFTInfo memory nftInfo) external payable;
}
