// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { NFTInfo } from "../../libraries/Struct.sol";

/**
 * @title IPuzzleXNFTSettingSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IPuzzleXNFTSettingSystem {
  function setup(NFTInfo memory nftInfo, uint256 ticket, uint256 numOfGames, uint256 preRound, uint256 pieces) external;

  function startRound(NFTInfo memory nftInfo) external;
}
