// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IPuzzleXSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IPuzzleXSystem {
  function createGame(uint256 grid) external;

  function move(uint256[] memory indexX, uint256[] memory indexY) external;
}
